version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html

  php:
    build: ./php
    env_file: .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - ./data/html:/var/www/html

  db:
    image: hypriot/rpi-mysql
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql

volumes:
    db-data:
